### ISSUE TITLE
Adapting your source to list videos.

### ISSUE THREAD

**Issue by MRJALG** [ZiTAL/youtube-php-cli#1]
The PHP script you have created is perfect, the fundamental structure to authenticate via OAuth2 then save the refresh token to allow further use without having to re-authenticate in browser is flawless however I do not need to upload YouTube Videos, I would like to List my Uploads.

Would you be open to adding this functionality;

https://github.com/youtube/api-samples/blob/master/php/my_uploads.php

Of course, you will be compensated in advance for your time. I cannot find anybody who understands what I need, so I guess my best chance is asking you. Thank you and please get back to me.

**Comment by MRJALG** [comment]
> The PHP script you have created is perfect, the fundamental structure to authenticate via OAuth2 then save the refresh token to allow further use without having to re-authenticate in browser is flawless however I do not need to upload YouTube Videos, I would like to List my Uploads.
> 
> Would you be open to adding this functionality;
> 
> https://github.com/youtube/api-samples/blob/master/php/my_uploads.php
> 
> Of course, you will be compensated in advance for your time. I cannot find anybody who understands what I need, so I guess my best chance is asking you. Thank you and please get back to me.

**Comment by ZiTAL** [comment]
I make the project up again, i will check it

Hau idatzi du ZiTAL %^D (zitalman@gmail.com) erabiltzaileak (2018 abe. 26,
az. (10:22)):

**Comment by ZiTAL** [comment]
I uploaded list.php I wish you like it

https://github.com/ZiTAL/youtube-php-cli/blob/master/list.php

Hau idatzi du ZiTAL %^D (zitalman@gmail.com) erabiltzaileak (2018 abe. 26,
az. (13:10)):
